export const LANGUAGES = [
  { code: 'ar', label: 'عربي', dir: 'rtl' },
  { code: 'fr', label: 'FR', dir: 'ltr' },
  { code: 'en', label: 'EN', dir: 'ltr' },
];

export const ATTRIBUTE_OPTIONS = {
  ar: [
    { value: 'صاحب الفكرة', label: 'صاحب الفكرة' },
    { value: 'المساعد الأول', label: 'المساعد الأول' },
    { value: 'رئيس الوفد', label: 'رئيس الوفد' },
    { value: 'سائق', label: 'سائق' },
  ],
  fr: [
    { value: 'Porteur de l\'idée', label: 'Porteur de l\'idée' },
    { value: 'Premier Assistant', label: 'Premier Assistant' },
    { value: 'Chef de Délégation', label: 'Chef de Délégation' },
    { value: 'Chauffeur', label: 'Chauffeur' },
  ],
  en: [
    { value: 'Idea Owner', label: 'Idea Owner' },
    { value: 'First Assistant', label: 'First Assistant' },
    { value: 'Head of Delegation', label: 'Head of Delegation' },
    { value: 'Driver', label: 'Driver' },
  ],
};

export const AXIS_OPTIONS = {
  ar: [
    { value: 'الابتكار التكنولوجي الطلابي', label: 'الابتكار التكنولوجي الطلابي' },
    { value: 'الابتكار التكنولوجي في المجال الزراعي', label: 'الابتكار التكنولوجي في المجال الزراعي' },
  ],
  fr: [
    { value: 'Innovation Technologique Étudiante', label: 'Innovation Technologique Étudiante' },
    { value: 'Innovation Technologique Agricole', label: 'Innovation Technologique Agricole' },
  ],
  en: [
    { value: 'Student Technological Innovation', label: 'Student Technological Innovation' },
    { value: 'Agricultural Technological Innovation', label: 'Agricultural Technological Innovation' },
  ],
};

export const AXIS_GROUP_MAP = {
  'الابتكار التكنولوجي الطلابي': 'axis_student',
  'الابتكار التكنولوجي في المجال الزراعي': 'axis_agricultural',
  'Innovation Technologique Étudiante': 'axis_student',
  'Innovation Technologique Agricole': 'axis_agricultural',
  'Student Technological Innovation': 'axis_student',
  'Agricultural Technological Innovation': 'axis_agricultural',
};

export const AXIS_DISPLAY_NAMES = {
  ar: {
    'axis_student': 'الابتكار التكنولوجي الطلابي',
    'axis_agricultural': 'الابتكار التكنولوجي في المجال الزراعي',
  },
  fr: {
    'axis_student': 'Innovation Technologique Étudiante',
    'axis_agricultural': 'Innovation Technologique Agricole',
  },
  en: {
    'axis_student': 'Student Technological Innovation',
    'axis_agricultural': 'Agricultural Technological Innovation',
  },
};

export const DASHBOARD_CONTENT = {
  ar: {
    dashboard: 'لوحة التحكم',
    totalParticipants: 'إجمالي المشاركين',
    present: 'حاضر',
    absent: 'غائب',
    attendanceRate: 'نسبة الحضور',
    overview: 'نظرة عامة',
    recentParticipants: 'أحدث المشاركين',
    latestMembers: 'أحدث الأعضاء المسجلين',
    viewAll: 'عرض الكل',
    live: 'مباشر',
    total: 'الإجمالي',
    delete: 'حذف',
    
    boys: 'قائمة الأولاد',
    girls: 'قائمة البنات',
    addMember: 'إضافة عضو',
    manageMale: 'إدارة المشاركين الذكور',
    manageFemale: 'إدارة المشاركات الإناث',
    members: 'أعضاء',
    filter: 'تصفية',
    searchPlaceholder: 'بحث بالاسم، الرقم الجامعي، الهاتف، البريد، الجامعة، النادي...',
    
    name: 'الاسم',
    university: 'الجامعة',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    axis: 'محور المسابقة',
    club: 'النادي',
    attribute: 'الصفة',
    status: 'الحالة',
    attendanceTime: 'وقت الحضور',
    actions: 'الإجراءات',
    notPresent: 'غير حاضر',
    presentStatus: 'حاضر',
    showing: 'عرض',
    of: 'من',
    participants: 'مشارك',
    previous: 'السابق',
    next: 'التالي',
    
    addTitle: 'إضافة عضو جديد',
    editTitle: 'تعديل العضو',
    addSubtitle: 'قم بتعبئة التفاصيل لإضافة عضو جديد',
    editSubtitle: 'تحديث معلومات العضو',
    fullName: 'الاسم الكامل',
    universityName: 'اسم الجامعة',
    matricule: 'الرقم الجامعي',
    phoneNumber: 'رقم الهاتف',
    emailAddress: 'البريد الإلكتروني',
    competitionAxis: 'محور المسابقة',
    clubName: 'اسم النادي',
    attributeLabel: 'الصفة',
    genderLabel: 'الجنس',
    boy: 'ولد',
    girl: 'بنت',
    autoSet: 'يتم التعيين تلقائياً',
    updateParticipant: 'تحديث العضو',
    addParticipant: 'إضافة عضو',
    cancel: 'إلغاء',
    saving: 'جاري الحفظ...',
    
    vsLastWeek: 'مقارنة بالأسبوع الماضي',
    totalMembers: 'إجمالي الأعضاء',
    attendanceRateLabel: 'نسبة الحضور',
    genderDistribution: 'توزيع الجنسين',
    boysVsGirls: 'أولاد مقابل بنات',
    girlsAttendance: 'حضور البنات',
    femaleParticipants: 'مشاركات إناث',
    
    deleteConfirm: 'هل أنت متأكد من حذف هذا العضو؟',
    deleteSuccess: 'تم حذف العضو بنجاح',
    deleteError: 'فشل حذف العضو',
    validateSuccess: 'تم تأكيد الحضور بنجاح',
    validateError: 'فشل تأكيد الحضور',
    alreadyPresent: 'العضو حاضر بالفعل',
    addSuccess: 'تم إضافة العضو بنجاح',
    addError: 'فشل إضافة العضو',
    updateSuccess: 'تم تحديث العضو بنجاح',
    updateError: 'فشل تحديث العضو',
    noParticipants: 'لا يوجد مشاركين',
    addFirstParticipant: 'أضف أول مشارك',
    startFirstRoster: 'ابدأ قائمتك الأولى',
    addParticipantToStart: 'أضف مشاركاً لبدء تتبع الحضور',
  },
  fr: {
    dashboard: 'Tableau de Bord',
    totalParticipants: 'Total Participants',
    present: 'Présent',
    absent: 'Absent',
    attendanceRate: "Taux d'Présence",
    overview: 'Aperçu',
    recentParticipants: 'Participants Récents',
    latestMembers: 'Derniers membres inscrits',
    viewAll: 'Voir tout',
    live: 'En direct',
    total: 'Total',
    delete: 'Supprimer',
    
    boys: 'Liste des Garçons',
    girls: 'Liste des Filles',
    addMember: 'Ajouter un Membre',
    manageMale: 'Gérer les participants masculins',
    manageFemale: 'Gérer les participantes féminines',
    members: 'membres',
    filter: 'Filtrer',
    searchPlaceholder: 'Rechercher par nom, matricule, téléphone, email, université, club...',
    
    name: 'Nom',
    university: 'Université',
    phone: 'Téléphone',
    email: 'Email',
    axis: "Axe de Compétition",
    club: 'Club',
    attribute: 'Attribut',
    status: 'Statut',
    attendanceTime: "Heure d'Présence",
    actions: 'Actions',
    notPresent: 'Non Présent',
    presentStatus: 'Présent',
    showing: 'Affichage',
    of: 'de',
    participants: 'participants',
    previous: 'Précédent',
    next: 'Suivant',
    
    addTitle: 'Ajouter un Nouveau Membre',
    editTitle: 'Modifier le Membre',
    addSubtitle: 'Remplissez les détails pour ajouter un nouveau membre',
    editSubtitle: 'Mettre à jour les informations du membre',
    fullName: 'Nom Complet',
    universityName: "Nom de l'Université",
    matricule: 'Matricule',
    phoneNumber: 'Numéro de Téléphone',
    emailAddress: 'Adresse Email',
    competitionAxis: "Axe de Compétition",
    clubName: "Nom du Club",
    attributeLabel: 'Attribut',
    genderLabel: 'Genre',
    boy: 'Garçon',
    girl: 'Fille',
    autoSet: 'Défini automatiquement',
    updateParticipant: 'Mettre à jour',
    addParticipant: 'Ajouter',
    cancel: 'Annuler',
    saving: 'Enregistrement...',
    
    vsLastWeek: 'vs semaine dernière',
    totalMembers: 'Total membres',
    attendanceRateLabel: "Taux d'présence",
    genderDistribution: 'Distribution des genres',
    boysVsGirls: 'Garçons vs Filles',
    girlsAttendance: 'Présence des filles',
    femaleParticipants: 'Participantes féminines',
    
    deleteConfirm: 'Voulez-vous vraiment supprimer ce membre ?',
    deleteSuccess: 'Membre supprimé avec succès',
    deleteError: 'Échec de la suppression',
    validateSuccess: 'Présence validée avec succès',
    validateError: 'Échec de la validation',
    alreadyPresent: 'Le membre est déjà présent',
    addSuccess: 'Membre ajouté avec succès',
    addError: "Échec de l'ajout",
    updateSuccess: 'Membre mis à jour avec succès',
    updateError: 'Échec de la mise à jour',
    noParticipants: 'Aucun participant',
    addFirstParticipant: 'Ajouter votre premier participant',
    startFirstRoster: 'Commencez votre premier roster',
    addParticipantToStart: 'Ajoutez un participant pour commencer le suivi',
  },
  en: {
    dashboard: 'Dashboard',
    totalParticipants: 'Total Participants',
    present: 'Present',
    absent: 'Absent',
    attendanceRate: 'Attendance Rate',
    overview: 'Overview',
    recentParticipants: 'Recent Participants',
    latestMembers: 'Latest registered members',
    viewAll: 'View All',
    live: 'Live',
    total: 'Total',
    delete: 'Delete',
    
    boys: 'Boys List',
    girls: 'Girls List',
    addMember: 'Add Member',
    manageMale: 'Manage male participants',
    manageFemale: 'Manage female participants',
    members: 'members',
    filter: 'Filter',
    searchPlaceholder: 'Search by name, matricule, phone, email, university, club...',
    
    name: 'Name',
    university: 'University',
    phone: 'Phone',
    email: 'Email',
    axis: 'Competition Axis',
    club: 'Club',
    attribute: 'Attribute',
    status: 'Status',
    attendanceTime: 'Attendance Time',
    actions: 'Actions',
    notPresent: 'Not Present',
    presentStatus: 'Present',
    showing: 'Showing',
    of: 'of',
    participants: 'participants',
    previous: 'Previous',
    next: 'Next',
    
    addTitle: 'Add New Member',
    editTitle: 'Edit Member',
    addSubtitle: 'Fill in the details to add a new member',
    editSubtitle: 'Update participant information',
    fullName: 'Full Name',
    universityName: 'University Name',
    matricule: 'Matricule',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    competitionAxis: 'Competition Axis',
    clubName: 'Club Name',
    attributeLabel: 'Attribute',
    genderLabel: 'Gender',
    boy: 'Boy',
    girl: 'Girl',
    autoSet: 'Auto-set based on list',
    updateParticipant: 'Update Participant',
    addParticipant: 'Add Participant',
    cancel: 'Cancel',
    saving: 'Saving...',
    
    vsLastWeek: 'vs last week',
    totalMembers: 'Total Members',
    attendanceRateLabel: 'Attendance Rate',
    genderDistribution: 'Gender Distribution',
    boysVsGirls: 'Boys vs Girls',
    girlsAttendance: 'Girls Attendance',
    femaleParticipants: 'Female participants',
    
    deleteConfirm: 'Are you sure you want to delete this member?',
    deleteSuccess: 'Member deleted successfully',
    deleteError: 'Failed to delete member',
    validateSuccess: 'Attendance validated successfully',
    validateError: 'Failed to validate attendance',
    alreadyPresent: 'Member is already present',
    addSuccess: 'Member added successfully',
    addError: 'Failed to add member',
    updateSuccess: 'Member updated successfully',
    updateError: 'Failed to update member',
    noParticipants: 'No participants',
    addFirstParticipant: 'Add your first participant',
    startFirstRoster: 'Start your first roster',
    addParticipantToStart: 'Add a participant to start tracking attendance',
  },
};